CC = gcc
CFLAGS = -Wall

all: out/waitforinput out/splitpoem out/countforever out/takeover

out/waitforinput: waitforinput.c
	$(CC) $(CFLAGS) -o $@ $<

out/splitpoem: splitpoem.c
	$(CC) $(CFLAGS) -o $@ $<

out/countforever: countforever.c
	$(CC) $(CFLAGS) -o $@ $<

out/takeover: takeover.c
	$(CC) $(CFLAGS) -o $@ $<
